// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// UsersGet implements GET /users operation.
//
// Returns a list of users.
//
// GET /users
func (UnimplementedHandler) UsersGet(ctx context.Context) (r []string, _ error) {
	return r, ht.ErrNotImplemented
}
