/*
Shopping List API

User login request structure

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MainShoppingListPatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MainShoppingListPatch{}

// MainShoppingListPatch Partial shopping list update structure
type MainShoppingListPatch struct {
	Items []string `json:"items,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewMainShoppingListPatch instantiates a new MainShoppingListPatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMainShoppingListPatch() *MainShoppingListPatch {
	this := MainShoppingListPatch{}
	return &this
}

// NewMainShoppingListPatchWithDefaults instantiates a new MainShoppingListPatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMainShoppingListPatchWithDefaults() *MainShoppingListPatch {
	this := MainShoppingListPatch{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *MainShoppingListPatch) GetItems() []string {
	if o == nil || IsNil(o.Items) {
		var ret []string
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainShoppingListPatch) GetItemsOk() ([]string, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *MainShoppingListPatch) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []string and assigns it to the Items field.
func (o *MainShoppingListPatch) SetItems(v []string) {
	o.Items = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MainShoppingListPatch) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainShoppingListPatch) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MainShoppingListPatch) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MainShoppingListPatch) SetName(v string) {
	o.Name = &v
}

func (o MainShoppingListPatch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MainShoppingListPatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableMainShoppingListPatch struct {
	value *MainShoppingListPatch
	isSet bool
}

func (v NullableMainShoppingListPatch) Get() *MainShoppingListPatch {
	return v.value
}

func (v *NullableMainShoppingListPatch) Set(val *MainShoppingListPatch) {
	v.value = val
	v.isSet = true
}

func (v NullableMainShoppingListPatch) IsSet() bool {
	return v.isSet
}

func (v *NullableMainShoppingListPatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMainShoppingListPatch(val *MainShoppingListPatch) *NullableMainShoppingListPatch {
	return &NullableMainShoppingListPatch{value: val, isSet: true}
}

func (v NullableMainShoppingListPatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMainShoppingListPatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


