/*
Shopping List API

User login request structure

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MainLoginRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MainLoginRequest{}

// MainLoginRequest User login request structure
type MainLoginRequest struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// NewMainLoginRequest instantiates a new MainLoginRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMainLoginRequest() *MainLoginRequest {
	this := MainLoginRequest{}
	return &this
}

// NewMainLoginRequestWithDefaults instantiates a new MainLoginRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMainLoginRequestWithDefaults() *MainLoginRequest {
	this := MainLoginRequest{}
	return &this
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *MainLoginRequest) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainLoginRequest) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *MainLoginRequest) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *MainLoginRequest) SetPassword(v string) {
	o.Password = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *MainLoginRequest) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MainLoginRequest) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *MainLoginRequest) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *MainLoginRequest) SetUsername(v string) {
	o.Username = &v
}

func (o MainLoginRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MainLoginRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

type NullableMainLoginRequest struct {
	value *MainLoginRequest
	isSet bool
}

func (v NullableMainLoginRequest) Get() *MainLoginRequest {
	return v.value
}

func (v *NullableMainLoginRequest) Set(val *MainLoginRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMainLoginRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMainLoginRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMainLoginRequest(val *MainLoginRequest) *NullableMainLoginRequest {
	return &NullableMainLoginRequest{value: val, isSet: true}
}

func (v NullableMainLoginRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMainLoginRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


