// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source repository.go -package main -destination repository_mock.go
//

// Package main is a generated GoMock package.
package main

import (
	reflect "reflect"

	opentracing "github.com/opentracing/opentracing-go"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AddSession mocks base method.
func (m *MockRepositoryInterface) AddSession(parentSpan opentracing.Span, username string) (*Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSession", parentSpan, username)
	ret0, _ := ret[0].(*Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSession indicates an expected call of AddSession.
func (mr *MockRepositoryInterfaceMockRecorder) AddSession(parentSpan, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSession", reflect.TypeOf((*MockRepositoryInterface)(nil).AddSession), parentSpan, username)
}

// CreateShoppingList mocks base method.
func (m *MockRepositoryInterface) CreateShoppingList(parentSpan opentracing.Span, list *ShoppingList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShoppingList", parentSpan, list)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateShoppingList indicates an expected call of CreateShoppingList.
func (mr *MockRepositoryInterfaceMockRecorder) CreateShoppingList(parentSpan, list any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShoppingList", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateShoppingList), parentSpan, list)
}

// DeleteShoppingList mocks base method.
func (m *MockRepositoryInterface) DeleteShoppingList(parentSpan opentracing.Span, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteShoppingList", parentSpan, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteShoppingList indicates an expected call of DeleteShoppingList.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteShoppingList(parentSpan, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteShoppingList", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteShoppingList), parentSpan, id)
}

// GetAllShoppingLists mocks base method.
func (m *MockRepositoryInterface) GetAllShoppingLists(parentSpan opentracing.Span) ([]ShoppingList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllShoppingLists", parentSpan)
	ret0, _ := ret[0].([]ShoppingList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllShoppingLists indicates an expected call of GetAllShoppingLists.
func (mr *MockRepositoryInterfaceMockRecorder) GetAllShoppingLists(parentSpan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllShoppingLists", reflect.TypeOf((*MockRepositoryInterface)(nil).GetAllShoppingLists), parentSpan)
}

// GetSession mocks base method.
func (m *MockRepositoryInterface) GetSession(parentSpan opentracing.Span, token string) (*Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", parentSpan, token)
	ret0, _ := ret[0].(*Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockRepositoryInterfaceMockRecorder) GetSession(parentSpan, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockRepositoryInterface)(nil).GetSession), parentSpan, token)
}

// GetShoppingList mocks base method.
func (m *MockRepositoryInterface) GetShoppingList(parentSpan opentracing.Span, id string) (*ShoppingList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShoppingList", parentSpan, id)
	ret0, _ := ret[0].(*ShoppingList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShoppingList indicates an expected call of GetShoppingList.
func (mr *MockRepositoryInterfaceMockRecorder) GetShoppingList(parentSpan, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShoppingList", reflect.TypeOf((*MockRepositoryInterface)(nil).GetShoppingList), parentSpan, id)
}

// Init mocks base method.
func (m *MockRepositoryInterface) Init() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init")
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockRepositoryInterfaceMockRecorder) Init() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockRepositoryInterface)(nil).Init))
}

// PatchShoppingList mocks base method.
func (m *MockRepositoryInterface) PatchShoppingList(parentSpan opentracing.Span, id string, patch *ShoppingListPatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchShoppingList", parentSpan, id, patch)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchShoppingList indicates an expected call of PatchShoppingList.
func (mr *MockRepositoryInterfaceMockRecorder) PatchShoppingList(parentSpan, id, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchShoppingList", reflect.TypeOf((*MockRepositoryInterface)(nil).PatchShoppingList), parentSpan, id, patch)
}

// UpdateShoppingList mocks base method.
func (m *MockRepositoryInterface) UpdateShoppingList(parentSpan opentracing.Span, id string, list *ShoppingList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShoppingList", parentSpan, id, list)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateShoppingList indicates an expected call of UpdateShoppingList.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateShoppingList(parentSpan, id, list any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShoppingList", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateShoppingList), parentSpan, id, list)
}
